/**
 * Seed Data for Firebase Emulators
 * This file contains sample data for testing the application
 */

export interface SeedUser {
  uid: string;
  email: string;
  password: string;
  displayName: string;
  photoURL: string;
  userType: 'pm' | 'mentor' | 'mentee';
  bio?: string;
  technologies?: Array<{ name: string; level: string }>;
  yearsOfExperience?: number;
  rating?: number;
  totalMentees?: number;
  department?: string;
  location?: string;
}

export const seedUsers: SeedUser[] = [
  // Project Managers
  {
    uid: 'pm-001',
    email: 'pm1@bairesdev.com',
    password: 'password123',
    displayName: 'Sarah Johnson',
    photoURL: 'https://i.pravatar.cc/150?img=1',
    userType: 'pm',
    bio: 'Senior Project Manager with 10+ years of experience managing tech teams',
    department: 'Engineering',
    location: 'San Francisco, CA',
  },
  {
    uid: 'pm-002',
    email: 'pm2@bairesdev.com',
    password: 'password123',
    displayName: 'Michael Chen',
    photoURL: 'https://i.pravatar.cc/150?img=12',
    userType: 'pm',
    bio: 'Agile PM specializing in cross-functional team coordination',
    department: 'Product',
    location: 'New York, NY',
  },

  // Mentors
  {
    uid: 'mentor-001',
    email: 'mentor1@bairesdev.com',
    password: 'password123',
    displayName: 'Dr. Emily Rodriguez',
    photoURL: 'https://i.pravatar.cc/150?img=5',
    userType: 'mentor',
    bio: 'Full-stack architect with deep expertise in React and Node.js. Passionate about teaching clean code principles.',
    yearsOfExperience: 12,
    rating: 4.9,
    totalMentees: 23,
    technologies: [
      { name: 'React', level: 'expert' },
      { name: 'Node.js', level: 'expert' },
      { name: 'TypeScript', level: 'expert' },
      { name: 'Database Design', level: 'advanced' },
      { name: 'Git/DevOps', level: 'advanced' },
    ],
    location: 'Austin, TX',
  },
  {
    uid: 'mentor-002',
    email: 'mentor2@bairesdev.com',
    password: 'password123',
    displayName: 'James Wilson',
    photoURL: 'https://i.pravatar.cc/150?img=13',
    userType: 'mentor',
    bio: 'Cloud Solutions Architect specializing in AWS and microservices. Love helping teams scale their applications.',
    yearsOfExperience: 10,
    rating: 4.8,
    totalMentees: 18,
    technologies: [
      { name: 'Cloud/AWS', level: 'expert' },
      { name: 'Python', level: 'expert' },
      { name: 'Database Design', level: 'expert' },
      { name: 'Git/DevOps', level: 'advanced' },
      { name: 'Kubernetes', level: 'advanced' },
    ],
    location: 'Seattle, WA',
  },
  {
    uid: 'mentor-003',
    email: 'mentor3@bairesdev.com',
    password: 'password123',
    displayName: 'Maria Garcia',
    photoURL: 'https://i.pravatar.cc/150?img=9',
    userType: 'mentor',
    bio: 'Mobile development expert with focus on React Native and Flutter. Experienced in building production apps.',
    yearsOfExperience: 8,
    rating: 4.7,
    totalMentees: 15,
    technologies: [
      { name: 'Mobile Dev', level: 'expert' },
      { name: 'React', level: 'expert' },
      { name: 'Flutter', level: 'advanced' },
      { name: 'React Native', level: 'expert' },
      { name: 'Git/DevOps', level: 'intermediate' },
    ],
    location: 'Miami, FL',
  },
  {
    uid: 'mentor-004',
    email: 'mentor4@bairesdev.com',
    password: 'password123',
    displayName: 'David Kim',
    photoURL: 'https://i.pravatar.cc/150?img=14',
    userType: 'mentor',
    bio: 'Frontend specialist passionate about UI/UX and modern JavaScript frameworks. Building beautiful interfaces for 9 years.',
    yearsOfExperience: 9,
    rating: 4.9,
    totalMentees: 20,
    technologies: [
      { name: 'Frontend', level: 'expert' },
      { name: 'React', level: 'expert' },
      { name: 'Vue.js', level: 'advanced' },
      { name: 'CSS/Tailwind', level: 'expert' },
      { name: 'TypeScript', level: 'advanced' },
    ],
    location: 'Los Angeles, CA',
  },
  {
    uid: 'mentor-005',
    email: 'mentor5@bairesdev.com',
    password: 'password123',
    displayName: 'Alex Thompson',
    photoURL: 'https://i.pravatar.cc/150?img=15',
    userType: 'mentor',
    bio: 'Backend engineer with strong background in system design and scalability. Expert in Node.js and Python.',
    yearsOfExperience: 11,
    rating: 4.8,
    totalMentees: 16,
    technologies: [
      { name: 'Node.js', level: 'expert' },
      { name: 'Python', level: 'expert' },
      { name: 'Database Design', level: 'expert' },
      { name: 'Git/DevOps', level: 'advanced' },
      { name: 'Microservices', level: 'expert' },
    ],
    location: 'Boston, MA',
  },

  // Mentees
  {
    uid: 'mentee-001',
    email: 'mentee1@bairesdev.com',
    password: 'password123',
    displayName: 'Jessica Martinez',
    photoURL: 'https://i.pravatar.cc/150?img=10',
    userType: 'mentee',
    bio: 'Junior Frontend Developer eager to learn React and modern web development',
    yearsOfExperience: 1,
    technologies: [
      { name: 'HTML/CSS', level: 'intermediate' },
      { name: 'JavaScript', level: 'beginner' },
      { name: 'React', level: 'beginner' },
    ],
    location: 'Chicago, IL',
  },
  {
    uid: 'mentee-002',
    email: 'mentee2@bairesdev.com',
    password: 'password123',
    displayName: 'Ryan Patel',
    photoURL: 'https://i.pravatar.cc/150?img=11',
    userType: 'mentee',
    bio: 'Backend developer looking to improve Node.js and database skills',
    yearsOfExperience: 2,
    technologies: [
      { name: 'Node.js', level: 'beginner' },
      { name: 'JavaScript', level: 'intermediate' },
      { name: 'Database Design', level: 'beginner' },
    ],
    location: 'Denver, CO',
  },
  {
    uid: 'mentee-003',
    email: 'mentee3@bairesdev.com',
    password: 'password123',
    displayName: 'Sophie Anderson',
    photoURL: 'https://i.pravatar.cc/150?img=16',
    userType: 'mentee',
    bio: 'Full-stack junior dev wanting to learn cloud deployment and DevOps',
    yearsOfExperience: 1.5,
    technologies: [
      { name: 'React', level: 'intermediate' },
      { name: 'Node.js', level: 'beginner' },
      { name: 'Cloud/AWS', level: 'beginner' },
    ],
    location: 'Portland, OR',
  },
  {
    uid: 'mentee-004',
    email: 'mentee4@bairesdev.com',
    password: 'password123',
    displayName: 'Carlos Mendez',
    photoURL: 'https://i.pravatar.cc/150?img=17',
    userType: 'mentee',
    bio: 'Mobile development enthusiast learning React Native',
    yearsOfExperience: 1,
    technologies: [
      { name: 'React', level: 'beginner' },
      { name: 'Mobile Dev', level: 'beginner' },
      { name: 'JavaScript', level: 'intermediate' },
    ],
    location: 'Phoenix, AZ',
  },
  {
    uid: 'mentee-005',
    email: 'mentee5@bairesdev.com',
    password: 'password123',
    displayName: 'Emma Taylor',
    photoURL: 'https://i.pravatar.cc/150?img=18',
    userType: 'mentee',
    bio: 'Computer Science graduate starting career in software development',
    yearsOfExperience: 0.5,
    technologies: [
      { name: 'Python', level: 'intermediate' },
      { name: 'Database Design', level: 'beginner' },
      { name: 'Git/DevOps', level: 'beginner' },
    ],
    location: 'Atlanta, GA',
  },
];

// Sample mentorships
export const seedMentorships = [
  {
    id: 'mentorship-001',
    projectManagerId: 'pm-001',
    projectManagerName: 'Sarah Johnson',
    mentorId: 'mentor-001',
    mentorName: 'Dr. Emily Rodriguez',
    mentorAvatar: 'https://i.pravatar.cc/150?img=5',
    menteeId: 'mentee-001',
    menteeName: 'Jessica Martinez',
    menteeAvatar: 'https://i.pravatar.cc/150?img=10',
    technologies: ['React', 'Frontend', 'TypeScript'],
    challengeDescription: 'Jessica needs help understanding React hooks, component architecture, and state management patterns for building scalable applications.',
    status: 'active',
    startDate: new Date('2024-10-01'),
    createdAt: new Date('2024-09-25'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'mentorship-002',
    projectManagerId: 'pm-001',
    projectManagerName: 'Sarah Johnson',
    mentorId: 'mentor-002',
    mentorName: 'James Wilson',
    mentorAvatar: 'https://i.pravatar.cc/150?img=13',
    menteeId: 'mentee-003',
    menteeName: 'Sophie Anderson',
    menteeAvatar: 'https://i.pravatar.cc/150?img=16',
    technologies: ['Cloud/AWS', 'DevOps', 'Database Design'],
    challengeDescription: 'Sophie wants to learn how to deploy applications to AWS, set up CI/CD pipelines, and understand cloud architecture best practices.',
    status: 'active',
    startDate: new Date('2024-10-05'),
    createdAt: new Date('2024-09-28'),
    updatedAt: new Date('2024-10-19'),
  },
  {
    id: 'mentorship-003',
    projectManagerId: 'pm-002',
    projectManagerName: 'Michael Chen',
    mentorId: 'mentor-003',
    mentorName: 'Maria Garcia',
    mentorAvatar: 'https://i.pravatar.cc/150?img=9',
    menteeId: 'mentee-004',
    menteeName: 'Carlos Mendez',
    menteeAvatar: 'https://i.pravatar.cc/150?img=17',
    technologies: ['Mobile Dev', 'React Native'],
    challengeDescription: 'Carlos is transitioning from web to mobile development and needs guidance on React Native best practices and mobile-specific patterns.',
    status: 'pending_kickoff',
    createdAt: new Date('2024-10-18'),
    updatedAt: new Date('2024-10-18'),
  },
];

// Sample meetings
export const seedMeetings = [
  {
    id: 'meeting-001',
    mentorshipId: 'mentorship-001',
    mentorId: 'mentor-001',
    menteeId: 'mentee-001',
    projectManagerId: 'pm-001',
    participantIds: ['mentor-001', 'mentee-001', 'pm-001'],
    participantName: 'Dr. Emily Rodriguez',
    participantPhoto: 'https://i.pravatar.cc/150?img=5',
    title: 'Kickoff Meeting',
    type: 'kickoff',
    scheduledDate: new Date('2024-10-01T10:00:00'),
    duration: 60,
    status: 'completed',
    notes: 'Introduction meeting. Discussed learning goals and established weekly meeting schedule.',
    createdAt: new Date('2024-09-25'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'meeting-002',
    mentorshipId: 'mentorship-001',
    mentorId: 'mentor-001',
    menteeId: 'mentee-001',
    projectManagerId: 'pm-001',
    participantIds: ['mentor-001', 'mentee-001'],
    participantName: 'Dr. Emily Rodriguez',
    participantPhoto: 'https://i.pravatar.cc/150?img=5',
    title: 'React Hooks Deep Dive',
    type: 'regular',
    scheduledDate: new Date('2024-10-08T10:00:00'),
    duration: 60,
    status: 'completed',
    notes: 'Covered useState, useEffect, and custom hooks. Jessica practiced with real examples.',
    createdAt: new Date('2024-10-02'),
    updatedAt: new Date('2024-10-08'),
  },
  {
    id: 'meeting-003',
    mentorshipId: 'mentorship-001',
    mentorId: 'mentor-001',
    menteeId: 'mentee-001',
    projectManagerId: 'pm-001',
    participantIds: ['mentor-001', 'mentee-001'],
    participantName: 'Dr. Emily Rodriguez',
    participantPhoto: 'https://i.pravatar.cc/150?img=5',
    title: 'State Management Patterns',
    type: 'regular',
    scheduledDate: new Date('2024-10-26T14:00:00'),
    duration: 60,
    status: 'scheduled',
    notes: 'Will discuss Context API, Redux basics, and when to use each approach.',
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'meeting-004',
    mentorshipId: 'mentorship-002',
    mentorId: 'mentor-002',
    menteeId: 'mentee-003',
    projectManagerId: 'pm-001',
    participantIds: ['mentor-002', 'mentee-003', 'pm-001'],
    participantName: 'James Wilson',
    participantPhoto: 'https://i.pravatar.cc/150?img=13',
    title: 'Kickoff Meeting',
    type: 'kickoff',
    scheduledDate: new Date('2024-10-05T15:00:00'),
    duration: 60,
    status: 'completed',
    notes: 'Discussed AWS fundamentals and created a learning roadmap for the next 3 months.',
    createdAt: new Date('2024-09-28'),
    updatedAt: new Date('2024-10-05'),
  },
  {
    id: 'meeting-005',
    mentorshipId: 'mentorship-003',
    mentorId: 'mentor-003',
    menteeId: 'mentee-004',
    projectManagerId: 'pm-002',
    participantIds: ['mentor-003', 'mentee-004', 'pm-002'],
    participantName: 'Maria Garcia',
    participantPhoto: 'https://i.pravatar.cc/150?img=9',
    title: 'Kickoff Meeting',
    type: 'kickoff',
    scheduledDate: new Date('2024-10-27T11:00:00'),
    duration: 60,
    status: 'pending_acceptance',
    notes: 'Initial meeting to discuss mobile development goals and expectations.',
    createdAt: new Date('2024-10-18'),
    updatedAt: new Date('2024-10-18'),
  },
];

