// Export all components from a central location
export { default as Avatar } from './Avatar'
export { default as Badge } from './Badge'
export { default as Button } from './Button'
export { default as Card } from './Card'
export { default as ProgressBar } from './ProgressBar'
export { default as StatCard } from './StatCard'
export { default as ActivityItem } from './ActivityItem'
export { default as Sidebar } from './Sidebar'
export { default as SEO } from './SEO'
export { default as AIChatModal } from './AIChatModal'
export { default as EmptyState } from './EmptyState'
export { default as PageHeader } from './PageHeader'
export { default as MentorshipResume } from './MentorshipResume'
export { default as MentorSelectionStep } from './MentorSelectionStep'
export { ProtectedRoute, PublicRoute } from './ProtectedRoute'
export { ProtectedLink, ProtectedButton, Protected } from './ProtectedLink'
export { default as PermissionRoute } from './PermissionRoute'

// Dashboard components
export { default as MentorDashboard } from './dashboard/MentorDashboard'
export { default as PMDashboard } from './dashboard/PMDashboard'
export { default as MenteeDashboard } from './dashboard/MenteeDashboard'
